//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Clinica_Progra_IVEntities : DbContext
    {
        public Clinica_Progra_IVEntities()
            : base("name=Clinica_Progra_IVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda_TB> Agenda_TB { get; set; }
        public virtual DbSet<Citas_TB> Citas_TB { get; set; }
        public virtual DbSet<Clientes_Padecimientos_TB> Clientes_Padecimientos_TB { get; set; }
        public virtual DbSet<Consultorio_TB> Consultorio_TB { get; set; }
        public virtual DbSet<Empleados_TB> Empleados_TB { get; set; }
        public virtual DbSet<Especialidades_TB> Especialidades_TB { get; set; }
        public virtual DbSet<Facturas_TB> Facturas_TB { get; set; }
        public virtual DbSet<Medicos_Especialidades_TB> Medicos_Especialidades_TB { get; set; }
        public virtual DbSet<Medicos_TB> Medicos_TB { get; set; }
        public virtual DbSet<Metodos_Pago_TB> Metodos_Pago_TB { get; set; }
        public virtual DbSet<Padecimientos_TB> Padecimientos_TB { get; set; }
        public virtual DbSet<Procedimientos_TB> Procedimientos_TB { get; set; }
        public virtual DbSet<Tipos_Perfiles_TB> Tipos_Perfiles_TB { get; set; }
        public virtual DbSet<Usuarios_TB> Usuarios_TB { get; set; }
        public virtual DbSet<Horarios_TB> Horarios_TB { get; set; }
        public virtual DbSet<Tarjetas_TB> Tarjetas_TB { get; set; }
        public virtual DbSet<Clientes_TB> Clientes_TB { get; set; }
    }
}
